import { StyleSheet } from 'react-native';
import { Colors, Radius, Shadows, Spacing } from './index';

/**
 * Centralized stylesheets for all screens and components.
 * Each namespace keeps the EXACT keys of the file it came from, so
 * consumers import it aliased: `import { alertsStyles as styles } from '../theme/styles'`.
 */

/* ───────────────────────── CameraThumbnail ───────────────────────── */

export const cameraThumbnailStyles = StyleSheet.create({
  thumb: {
    backgroundColor: Colors.surfaceDark,
    borderRadius: 12,
    overflow: 'hidden',
    justifyContent: 'space-between',
  },
  scanLines: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    opacity: 0.5,
  },
  thumbHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 10,
  },
  camName: {
    color: Colors.white,
    fontSize: 13,
    fontWeight: '600',
    flexShrink: 1,
    marginRight: 8,
  },
  recTag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,59,48,0.25)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  recDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: Colors.recordingRed,
    marginRight: 4,
  },
  recText: {
    color: Colors.recordingRed,
    fontSize: 9,
    fontWeight: '700',
  },
  thumbCenter: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  videoPlane: {
    width: 120,
    height: 60,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: Colors.gridLines,
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoLabel: {
    color: 'rgba(255,255,255,0.45)',
    fontSize: 11,
  },
  offlineText: {
    color: Colors.textMuted,
    fontSize: 12,
    marginTop: 8,
  },
  offlineOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(18,21,31,0.65)',
  },
  thumbFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 10,
  },
  thumbMeta: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 11,
    flexShrink: 1,
    marginLeft: 8,
  },
});

/* ───────────────────────── common ───────────────────────── */

export const commonStyles = StyleSheet.create({
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    paddingHorizontal: Spacing.sm,
    paddingVertical: 3,
    borderRadius: Radius.full,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginRight: 5,
  },
  badgeText: {
    fontSize: 11,
    fontWeight: '600',
  },
  typeIcon: {
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statCard: {
    flex: 1,
    backgroundColor: Colors.surface,
    borderRadius: Radius.md,
    padding: Spacing.md,
    margin: 6,
    ...Shadows.card,
  },
  statAccent: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 3,
    borderTopLeftRadius: Radius.md,
    borderTopRightRadius: Radius.md,
  },
  statValue: {
    fontSize: 20,
    fontWeight: '800',
    color: Colors.text,
  },
  statSuffix: {
    fontSize: 12,
    color: Colors.textMuted,
    fontWeight: '600',
    marginLeft: 2,
  },
  statLabel: {
    fontSize: 12,
    color: Colors.textMuted,
    marginTop: 2,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.sm + 4,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: Colors.text,
  },
  sectionAction: {
    fontSize: 13,
    color: Colors.primary,
    fontWeight: '600',
  },
});

/* ───────────────────────── FormField / Auth ───────────────────────── */

export const formFieldStyles = StyleSheet.create({
  flex: { flex: 1 },
  container: {
    flexGrow: 1,
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.md,
  },
  brand: { alignItems: 'center', marginTop: Spacing.xl },
  logo: {
    width: 64,
    height: 64,
    borderRadius: Radius.lg,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: Spacing.md,
  },
  title: { fontSize: 26, fontWeight: '800', color: Colors.text },
  subtitle: {
    fontSize: 14,
    color: Colors.textMuted,
    textAlign: 'center',
    marginTop: Spacing.xs,
    lineHeight: 20,
  },
  form: { marginTop: Spacing.xl },
  fieldWrap: { marginBottom: Spacing.md },
  label: {
    fontSize: 13,
    fontWeight: '600',
    color: Colors.text,
    marginBottom: 6,
  },
  inputBox: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
    backgroundColor: Colors.surface,
    paddingHorizontal: Spacing.md,
    minHeight: 50,
  },
  input: {
    flex: 1,
    marginLeft: Spacing.sm,
    color: Colors.text,
    fontSize: 15,
    paddingVertical: 12,
  },
  linkRow: { alignSelf: 'flex-end', marginBottom: Spacing.lg },
  link: { color: Colors.primary, fontSize: 13, fontWeight: '600' },
  primaryBtn: {
    backgroundColor: Colors.primary,
    borderRadius: Radius.md,
    minHeight: 52,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: Spacing.xs,
  },
  primaryBtnText: {
    color: Colors.white,
    fontSize: 16,
    fontWeight: '700',
  },
  btnDisabled: { opacity: 0.6 },
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: Spacing.lg,
    gap: Spacing.md,
  },
  dividerLine: { flex: 1, height: 1, backgroundColor: Colors.border },
  dividerText: { color: Colors.textMuted, fontSize: 13 },
  googleBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
    backgroundColor: Colors.surface,
    minHeight: 52,
    gap: Spacing.sm,
  },
  googleBtnText: { color: Colors.text, fontSize: 16, fontWeight: '600' },
  googleBtnLogo: { color: '#4285F4', fontSize: 20, fontWeight: '800' },
  footer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: Spacing.xl,
  },
  footerText: { color: Colors.textMuted, fontSize: 14 },
  footerLink: { color: Colors.primary, fontSize: 14, fontWeight: '700' },
  backBtn: { alignSelf: 'flex-start', marginTop: Spacing.sm },
  termsText: { color: Colors.textMuted, fontSize: 12, textAlign: 'center', marginTop: Spacing.md, lineHeight: 18 },
});

/* ───────────────────────── Login + Register (hanya `safe`) ───────────────────────── */

export const authScreenStyles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: Colors.background,
  },
});

/* ───────────────────────── RootNavigator (splash) ───────────────────────── */

export const rootNavigatorStyles = StyleSheet.create({
  splash: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.background,
    gap: 20,
  },
  splashLogo: {
    width: 72,
    height: 72,
    borderRadius: 20,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  splashText: { color: Colors.white, fontSize: 34, fontWeight: '900' },
});

/* ───────────────────────── AlertsScreen ───────────────────────── */

export const alertsStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.background },
  header: { paddingHorizontal: Spacing.md, paddingTop: Spacing.sm },
  title: { fontSize: 24, fontWeight: '800', color: Colors.text },
  subtitle: { fontSize: 13, color: Colors.textMuted, marginTop: 2 },
  filterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.md,
    marginTop: Spacing.md,
  },
  filterChip: {
    paddingHorizontal: Spacing.md,
    paddingVertical: 6,
    borderRadius: Radius.full,
    backgroundColor: Colors.surface,
    marginRight: Spacing.sm,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  filterChipActive: { backgroundColor: Colors.primary, borderColor: Colors.primary },
  filterText: { fontSize: 12, fontWeight: '600', color: Colors.textMuted },
  filterTextActive: { color: Colors.white },
  readAllBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 'auto',
    gap: 4,
  },
  readAllText: { fontSize: 12, fontWeight: '600', color: Colors.primary },
  list: { padding: Spacing.md, paddingBottom: Spacing.lg },
  alertCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: Colors.surface,
    borderRadius: Radius.lg,
    padding: Spacing.md,
    marginBottom: Spacing.sm + 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  alertUnread: {
    borderLeftWidth: 3,
    borderLeftColor: Colors.primary,
  },
  alertIcon: {
    width: 44,
    height: 44,
    borderRadius: Radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: Spacing.sm + 4,
  },
  alertBody: { flex: 1 },
  alertTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  typeTag: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
  },
  typeText: { fontSize: 10, fontWeight: '700' },
  timeText: { fontSize: 11, color: Colors.textMuted },
  alertMsg: { fontSize: 14, fontWeight: '600', color: Colors.text, lineHeight: 20 },
  camText: {
    fontSize: 12,
    color: Colors.textMuted,
    marginTop: 6,
  },
  unreadDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.primary,
    marginLeft: 6,
    marginTop: 4,
  },
  empty: { alignItems: 'center', marginTop: 60 },
  emptyText: { color: Colors.textMuted, marginTop: Spacing.sm + 4 },
});

/* ───────────────────────── CameraDetailScreen ───────────────────────── */

export const cameraDetailStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.background },
  content: { padding: Spacing.md, paddingBottom: Spacing.lg },
  missing: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.background,
  },
  missingText: { color: Colors.textMuted, fontSize: 15 },
  preview: {
    backgroundColor: Colors.surfaceDark,
    borderRadius: Radius.lg,
    overflow: 'hidden',
    minHeight: 220,
    justifyContent: 'space-between',
  },
  previewTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: Spacing.sm + 4,
  },
  previewLabel: { color: Colors.white, fontSize: 13, fontWeight: '600', flex: 1, marginRight: 8 },
  previewBadges: { flexDirection: 'row', gap: 6 },
  recTag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,59,48,0.25)',
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 4,
  },
  recDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: Colors.recordingRed,
    marginRight: 4,
  },
  recText: { color: Colors.recordingRed, fontSize: 9, fontWeight: '700' },
  previewCenter: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: Spacing.xl,
  },
  previewPlaceholder: { alignItems: 'center' },
  previewPlaceholderText: {
    color: 'rgba(255,255,255,0.4)',
    fontSize: 12,
    marginTop: 8,
  },
  previewBottom: {
    padding: Spacing.sm + 4,
    borderTopWidth: 1,
    borderTopColor: Colors.gridLines,
  },
  previewTime: { color: 'rgba(255,255,255,0.5)', fontSize: 11, textAlign: 'center' },
  actionRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginVertical: Spacing.md,
  },
  actionBtn: { alignItems: 'center' },
  actionBtnDisabled: { opacity: 0.5 },
  actionIcon: {
    width: 46,
    height: 46,
    borderRadius: Radius.md,
    backgroundColor: Colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  actionLabel: { fontSize: 11, fontWeight: '600', color: Colors.text },
  card: {
    backgroundColor: Colors.surface,
    borderRadius: Radius.lg,
    padding: Spacing.md,
    marginBottom: Spacing.md,
    ...Shadows.card,
  },
  cardTitle: { fontSize: 15, fontWeight: '700', color: Colors.text, marginBottom: Spacing.sm + 4 },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
  },
  detailLabel: { fontSize: 13, color: Colors.textMuted },
  detailValue: { fontSize: 13, fontWeight: '600', color: Colors.text },
  divider: { height: 1, backgroundColor: Colors.border, marginVertical: 2 },
  menuRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
  },
  menuLabel: {
    flex: 1,
    fontSize: 14,
    color: Colors.text,
    marginLeft: Spacing.sm + 4,
  },
  noRec: { fontSize: 13, color: Colors.textMuted, paddingVertical: Spacing.sm },
  recRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: Spacing.sm,
  },
  recThumb: {
    width: 42,
    height: 42,
    borderRadius: Radius.sm,
    backgroundColor: Colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: Spacing.sm + 4,
  },
  recInfo: { flex: 1 },
  recTitle: { fontSize: 13, fontWeight: '600', color: Colors.text },
  recMeta: { fontSize: 11, color: Colors.textMuted, marginTop: 2 },
});

/* ───────────────────────── CamerasScreen ───────────────────────── */

export const camerasStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.background },
  header: { paddingHorizontal: Spacing.md, paddingTop: Spacing.sm },
  title: { fontSize: 24, fontWeight: '800', color: Colors.text },
  subtitle: { fontSize: 13, color: Colors.textMuted, marginTop: 2 },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: Spacing.md,
    marginTop: Spacing.md,
    paddingHorizontal: Spacing.md,
    backgroundColor: Colors.surface,
    borderRadius: Radius.md,
    minHeight: 46,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  searchInput: {
    flex: 1,
    marginLeft: Spacing.sm,
    color: Colors.text,
    fontSize: 14,
    paddingVertical: 10,
  },
  filters: {
    flexDirection: 'row',
    paddingHorizontal: Spacing.md,
    marginTop: Spacing.sm + 4,
    marginBottom: Spacing.xs,
  },
  filterChip: {
    paddingHorizontal: Spacing.md,
    paddingVertical: 7,
    borderRadius: Radius.full,
    backgroundColor: Colors.surface,
    marginRight: Spacing.sm,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  filterChipActive: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  filterChipText: { fontSize: 12, fontWeight: '600', color: Colors.textMuted },
  filterChipTextActive: { color: Colors.white },
  list: { padding: Spacing.md, paddingBottom: Spacing.lg },
  cameraCard: { marginBottom: Spacing.md },
  empty: { alignItems: 'center', marginTop: 60 },
  emptyText: { color: Colors.textMuted, marginTop: Spacing.sm + 4 },
});

/* ───────────────────────── DashboardScreen ───────────────────────── */

export const dashboardStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.background },
  flex: { flex: 1 },
  content: { padding: Spacing.md, paddingBottom: Spacing.lg },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.lg,
  },
  headerText: { flex: 1, marginRight: Spacing.sm },
  greeting: { fontSize: 22, fontWeight: '800', color: Colors.text },
  subGreeting: { fontSize: 13, color: Colors.textMuted, marginTop: 2 },
  notifBtn: {
    width: 44,
    height: 44,
    borderRadius: Radius.md,
    backgroundColor: Colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    ...Shadows.card,
  },
  notifDot: {
    position: 'absolute',
    top: -2,
    right: -2,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: Colors.danger,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 3,
    borderWidth: 2,
    borderColor: Colors.background,
  },
  notifDotText: { color: Colors.white, fontSize: 9, fontWeight: '700' },
  emergencyCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.danger,
    borderRadius: Radius.lg,
    padding: Spacing.md,
    marginBottom: Spacing.md,
    ...Shadows.card,
  },
  emergencyIcon: {
    width: 44,
    height: 44,
    borderRadius: Radius.md,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: Spacing.sm + 4,
  },
  emergencyText: { flex: 1, marginRight: Spacing.sm },
  emergencyTitle: {
    color: Colors.white,
    fontSize: 16,
    fontWeight: '800',
  },
  emergencySub: {
    color: 'rgba(255,255,255,0.85)',
    fontSize: 12,
    marginTop: 2,
  },
  summaryCard: {
    backgroundColor: Colors.surface,
    borderRadius: Radius.lg,
    padding: Spacing.md,
    ...Shadows.card,
    marginBottom: Spacing.md,
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  summaryIcon: {
    width: 40,
    height: 40,
    borderRadius: Radius.md,
    backgroundColor: Colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: Spacing.sm + 4,
  },
  summaryText: { flex: 1 },
  summaryTitle: { fontSize: 15, fontWeight: '700', color: Colors.text },
  summarySub: { fontSize: 12, color: Colors.textMuted, marginTop: 2 },
  divider: {
    height: 1,
    backgroundColor: Colors.border,
    marginVertical: Spacing.md,
  },
  summaryQuick: { flexDirection: 'row' },
  quickItem: {
    flex: 1,
    alignItems: 'center',
    flexDirection: 'column',
    gap: 2,
  },
  quickDivider: {
    width: 1,
    backgroundColor: Colors.border,
    marginVertical: 4,
  },
  quickValue: { fontSize: 16, fontWeight: '800', color: Colors.text, marginTop: 4 },
  quickLabel: { fontSize: 11, color: Colors.textMuted },
  statsRow: {
    flexDirection: 'row',
    marginHorizontal: -6,
    marginBottom: Spacing.sm + 4,
  },
  miniCard: {
    width: 240,
    backgroundColor: Colors.surface,
    borderRadius: Radius.lg,
    padding: Spacing.sm,
    marginRight: Spacing.sm + 4,
    ...Shadows.card,
  },
  miniPreview: {
    height: 110,
    borderRadius: Radius.md,
    backgroundColor: Colors.surfaceDark,
    alignItems: 'center',
    justifyContent: 'center',
  },
  miniRec: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: Colors.recordingRed,
  },
  miniRecDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: Colors.recordingRed,
  },
  miniInfo: { padding: Spacing.sm },
  miniName: { fontSize: 14, fontWeight: '700', color: Colors.text },
  miniLoc: { fontSize: 11, color: Colors.textMuted, marginTop: 2 },
  alertRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.surface,
    borderRadius: Radius.md,
    padding: Spacing.md,
    marginBottom: Spacing.sm,
    ...Shadows.card,
  },
  alertRowUnread: {
    borderLeftWidth: 3,
    borderLeftColor: Colors.danger,
  },
  alertIcon: {
    width: 40,
    height: 40,
    borderRadius: Radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: Spacing.sm + 4,
  },
  alertBody: { flex: 1, marginRight: Spacing.sm },
  alertMsg: { fontSize: 13, fontWeight: '600', color: Colors.text, lineHeight: 18 },
  alertMeta: { fontSize: 11, color: Colors.textMuted, marginTop: 4 },
  emptyCameras: {
    backgroundColor: Colors.surface,
    borderRadius: Radius.lg,
    padding: Spacing.xl,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: Spacing.md,
  },
  emptyAlerts: {
    backgroundColor: Colors.surface,
    borderRadius: Radius.lg,
    padding: Spacing.xl,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: Spacing.md,
  },
  emptyText: { color: Colors.textMuted, marginTop: Spacing.sm + 4 },
});

/* ───────────────────────── LiveViewScreen ───────────────────────── */

export const liveViewStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.background },
  missing: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  missingText: { color: Colors.textMuted },
  stream: { backgroundColor: Colors.surfaceDark, flex: 1 },
  streamHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  iconBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  streamTitle: { flex: 1, marginHorizontal: Spacing.sm + 4 },
  streamName: { color: Colors.white, fontSize: 15, fontWeight: '700' },
  streamLoc: { color: 'rgba(255,255,255,0.55)', fontSize: 11, marginTop: 1 },
  streamActions: { flexDirection: 'row', gap: Spacing.sm },
  streamCenter: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  streamPlaceholder: {
    color: 'rgba(255,255,255,0.5)',
    fontSize: 14,
    marginTop: Spacing.sm + 4,
  },
  streamHint: {
    color: 'rgba(255,255,255,0.35)',
    fontSize: 12,
    marginTop: 4,
  },
  offlineText: {
    color: Colors.textMuted,
    fontSize: 15,
    marginTop: Spacing.sm + 4,
  },
  recTimer: {
    position: 'absolute',
    bottom: 44,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.6)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
  },
  recDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.recordingRed,
    marginRight: 6,
  },
  recTimerText: { color: Colors.white, fontSize: 12, fontVariant: ['tabular-nums'] },
  streamFooter: {
    padding: Spacing.sm + 4,
    alignItems: 'center',
  },
  footerText: {
    color: Colors.recordingRed,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1,
  },
  controls: {
    backgroundColor: Colors.surface,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingTop: Spacing.md,
  },
  controlBtn: { alignItems: 'center' },
  controlLabel: { fontSize: 11, color: Colors.textMuted, marginTop: 4 },
  recordBtn: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: Colors.recordingRed,
    alignItems: 'center',
    justifyContent: 'center',
  },
  recordBtnActive: { backgroundColor: Colors.textMuted },
  recordInner: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  recordDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: Colors.recordingRed,
  },
  recordLabel: {
    position: 'absolute',
    bottom: -18,
    fontSize: 10,
    color: Colors.text,
    fontWeight: '700',
  },
  retryBtn: {
    flexDirection: 'row',
    backgroundColor: Colors.primary,
    paddingHorizontal: Spacing.lg,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
  },
  retryText: { color: Colors.white, marginLeft: Spacing.sm, fontWeight: '700' },
});

/* ───────────────────────── PlaybackDetailScreen ───────────────────────── */

export const playbackDetailStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.background },
  stream: { backgroundColor: Colors.surfaceDark, flex: 1 },
  streamHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  iconBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  streamTitle: { flex: 1, marginHorizontal: Spacing.sm + 4 },
  streamName: { color: Colors.white, fontSize: 15, fontWeight: '700' },
  streamLoc: { color: 'rgba(255,255,255,0.55)', fontSize: 11, marginTop: 1 },
  streamCenter: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  playBig: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: 'rgba(255,255,255,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  streamHint: {
    color: 'rgba(255,255,255,0.4)',
    fontSize: 12,
    marginTop: Spacing.sm + 4,
  },
  timelineWrap: { paddingHorizontal: Spacing.md, paddingBottom: Spacing.md },
  timeline: {
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,0.2)',
    overflow: 'hidden',
    position: 'relative',
  },
  timelineFill: {
    height: 4,
    backgroundColor: Colors.primary,
    borderRadius: 2,
  },
  timelineThumb: {
    position: 'absolute',
    top: -4,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: Colors.white,
    marginLeft: -6,
  },
  timeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 6,
    alignItems: 'center',
  },
  timeText: { color: 'rgba(255,255,255,0.6)', fontSize: 11, fontVariant: ['tabular-nums'] },
  motionHint: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(245,158,11,0.15)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  motionText: { color: Colors.warning, fontSize: 10, fontWeight: '600' },
  controls: {
    backgroundColor: Colors.surface,
    paddingTop: Spacing.md,
    paddingHorizontal: Spacing.md,
  },
  speedRow: { flexDirection: 'row', justifyContent: 'center', marginBottom: Spacing.sm + 4 },
  speedChip: {
    paddingHorizontal: Spacing.md,
    paddingVertical: 5,
    borderRadius: 8,
    marginHorizontal: 4,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  speedChipActive: {
    backgroundColor: Colors.primarySoft,
    borderColor: Colors.primary,
  },
  speedText: { fontSize: 12, fontWeight: '700', color: Colors.textMuted },
  speedTextActive: { color: Colors.primary },
  controlRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  playBtn: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ctlBtn: { alignItems: 'center' },
  ctlLabel: { fontSize: 10, color: Colors.textMuted, marginTop: 4 },
});

/* ───────────────────────── PlaybackScreen ───────────────────────── */

export const playbackStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.background },
  header: { paddingHorizontal: Spacing.md, paddingTop: Spacing.sm },
  title: { fontSize: 24, fontWeight: '800', color: Colors.text },
  subtitle: { fontSize: 13, color: Colors.textMuted, marginTop: 2 },
  pickerRow: {
    flexDirection: 'row',
    paddingHorizontal: Spacing.md,
    marginTop: Spacing.md,
  },
  picker: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.full,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginRight: 6,
  },
  pickerActive: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  pickerText: { fontSize: 11, fontWeight: '600', color: Colors.text, marginLeft: 4 },
  pickerTextActive: { color: Colors.white },
  pickerDot: { width: 6, height: 6, borderRadius: 3 },
  dateRow: {
    flexDirection: 'row',
    paddingHorizontal: Spacing.md,
    marginTop: Spacing.sm,
    marginBottom: Spacing.xs,
  },
  dateChip: {
    paddingHorizontal: Spacing.md,
    paddingVertical: 6,
    borderRadius: Radius.sm,
    marginRight: Spacing.sm,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  dateChipActive: { backgroundColor: Colors.primarySoft, borderColor: Colors.primary },
  dateChipText: { fontSize: 12, fontWeight: '600', color: Colors.textMuted },
  dateChipTextActive: { color: Colors.primary },
  list: { padding: Spacing.md, paddingBottom: Spacing.lg },
  recCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.surface,
    borderRadius: Radius.lg,
    padding: Spacing.sm,
    marginBottom: Spacing.sm + 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 1,
  },
  thumb: {
    width: 96,
    height: 64,
    borderRadius: Radius.sm,
    backgroundColor: Colors.surfaceDark,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  durBadge: {
    position: 'absolute',
    bottom: 4,
    right: 4,
    backgroundColor: 'rgba(0,0,0,0.7)',
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 3,
  },
  durText: { color: Colors.white, fontSize: 9, fontWeight: '600' },
  motionBadge: {
    position: 'absolute',
    top: 4,
    left: 4,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(245,158,11,0.25)',
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 3,
    gap: 2,
  },
  motionText: { color: Colors.warning, fontSize: 8, fontWeight: '700' },
  recInfo: { flex: 1, marginLeft: Spacing.sm + 4, marginRight: Spacing.sm },
  recName: { fontSize: 14, fontWeight: '700', color: Colors.text },
  recLoc: { fontSize: 11, color: Colors.textMuted, marginTop: 2 },
  recMetaRow: { flexDirection: 'row', alignItems: 'center', marginTop: 6, flexWrap: 'wrap' },
  recMeta: { fontSize: 11, color: Colors.textMuted, marginLeft: 4 },
  empty: { alignItems: 'center', marginTop: 60 },
  emptyText: { color: Colors.textMuted, marginTop: Spacing.sm + 4 },
});

/* ───────────────────────── ProfileScreen ───────────────────────── */

export const profileStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.background },
  content: { padding: Spacing.md, paddingBottom: Spacing.lg },
  title: { fontSize: 24, fontWeight: '800', color: Colors.text, marginBottom: Spacing.md },
  profileCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.surface,
    borderRadius: Radius.lg,
    padding: Spacing.md,
    ...Shadows.card,
    marginBottom: Spacing.md,
  },
  avatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { color: Colors.white, fontSize: 24, fontWeight: '800' },
  profileInfo: { flex: 1, marginLeft: Spacing.md },
  profileName: { fontSize: 17, fontWeight: '800', color: Colors.text },
  profileEmail: { fontSize: 13, color: Colors.textMuted, marginTop: 2 },
  roleBadge: {
    alignSelf: 'flex-start',
    backgroundColor: Colors.primarySoft,
    borderRadius: Radius.full,
    paddingHorizontal: 10,
    paddingVertical: 3,
    marginTop: 6,
  },
  roleText: { fontSize: 11, fontWeight: '700', color: Colors.primary },
  group: { marginBottom: Spacing.md },
  groupTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: Colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 6,
    marginLeft: 4,
  },
  groupCard: {
    backgroundColor: Colors.surface,
    borderRadius: Radius.lg,
    paddingHorizontal: Spacing.md,
    ...Shadows.card,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
  },
  menuIcon: {
    width: 32,
    height: 32,
    borderRadius: Radius.sm,
    backgroundColor: Colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: Spacing.sm + 4,
  },
  menuLabel: { flex: 1, fontSize: 14, fontWeight: '600', color: Colors.text },
  menuValue: { fontSize: 12, color: Colors.textMuted, marginRight: 4 },
  divider: { height: 1, backgroundColor: Colors.border },
  logoutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FEE2E2',
    borderRadius: Radius.md,
    paddingVertical: 14,
    marginTop: Spacing.xs,
    gap: Spacing.sm,
  },
  logoutText: { color: Colors.danger, fontSize: 15, fontWeight: '700' },
  version: {
    textAlign: 'center',
    color: Colors.textMuted,
    fontSize: 11,
    marginTop: Spacing.md,
  },
  // Modal Edit Profil / Ganti Kata Sandi
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalCard: {
    backgroundColor: Colors.surface,
    borderTopLeftRadius: Radius.lg,
    borderTopRightRadius: Radius.lg,
    padding: Spacing.lg,
    paddingBottom: Spacing.xl,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: Colors.text,
    marginBottom: Spacing.md,
  },
  fieldWrap: { marginBottom: Spacing.md },
  fieldLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: Colors.text,
    marginBottom: 6,
  },
  fieldBox: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
    backgroundColor: Colors.background,
    paddingHorizontal: Spacing.md,
    minHeight: 50,
  },
  fieldInput: {
    flex: 1,
    color: Colors.text,
    fontSize: 15,
    paddingVertical: 12,
  },
  showPassRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: Spacing.md,
  },
  showPassText: { color: Colors.primary, fontSize: 13, fontWeight: '600' },
  modalActions: {
    flexDirection: 'row',
    gap: Spacing.sm,
    marginTop: Spacing.xs,
  },
  modalBtn: {
    flex: 1,
    minHeight: 50,
    borderRadius: Radius.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalCancel: { backgroundColor: Colors.background, borderWidth: 1, borderColor: Colors.border },
  modalCancelText: { color: Colors.text, fontSize: 15, fontWeight: '700' },
  modalPrimary: { backgroundColor: Colors.primary },
  modalPrimaryText: { color: Colors.white, fontSize: 15, fontWeight: '700' },
});

/* ───────────────────────── EmergencyScreen ───────────────────────── */

export const emergencyStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.background },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.md,
    paddingTop: Spacing.sm,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: Radius.md,
    backgroundColor: Colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: Spacing.sm + 4,
    ...Shadows.card,
  },
  headerText: { flex: 1 },
  title: { fontSize: 20, fontWeight: '800', color: Colors.text },
  subtitle: { fontSize: 13, color: Colors.textMuted, marginTop: 2 },
  content: { padding: Spacing.md, paddingBottom: Spacing.lg },
  hero: {
    backgroundColor: Colors.danger,
    borderRadius: Radius.lg,
    padding: Spacing.lg,
    alignItems: 'center',
    marginBottom: Spacing.md,
    ...Shadows.card,
  },
  heroIcon: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: Spacing.sm + 4,
  },
  heroTitle: {
    color: Colors.white,
    fontSize: 18,
    fontWeight: '800',
    textAlign: 'center',
  },
  heroSub: {
    color: 'rgba(255,255,255,0.85)',
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 19,
    marginTop: 4,
  },
  sectionLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: Colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 6,
    marginLeft: 4,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.surface,
    borderRadius: Radius.lg,
    padding: Spacing.md,
    marginBottom: Spacing.sm + 4,
    ...Shadows.card,
  },
  rowIcon: {
    width: 44,
    height: 44,
    borderRadius: Radius.md,
    backgroundColor: '#FEE2E2',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: Spacing.sm + 4,
  },
  rowInfo: { flex: 1 },
  rowName: { fontSize: 15, fontWeight: '700', color: Colors.text },
  rowRole: { fontSize: 12, color: Colors.textMuted, marginTop: 2 },
  rowPhone: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
    gap: 4,
  },
  rowPhoneText: {
    fontSize: 13,
    color: Colors.text,
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  note: {
    fontSize: 11,
    color: Colors.textMuted,
    textAlign: 'center',
    lineHeight: 16,
    marginTop: Spacing.sm + 4,
    paddingHorizontal: Spacing.md,
  },
});

/* ───────────────────────── SubscriptionScreen ───────────────────────── */

export const subscriptionStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.background },
  content: { padding: Spacing.md, paddingBottom: Spacing.lg },
  title: { fontSize: 24, fontWeight: '800', color: Colors.text },
  subtitle: { fontSize: 13, color: Colors.textMuted, marginTop: 2 },

  // kartu langganan aktif
  activeCard: {
    backgroundColor: Colors.primary,
    borderRadius: Radius.lg,
    padding: Spacing.md,
    marginTop: Spacing.md,
    ...Shadows.card,
  },
  activeTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  activeLabel: {
    color: 'rgba(255,255,255,0.75)',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  activePlan: { color: Colors.white, fontSize: 22, fontWeight: '800', marginTop: 4 },
  activeMeta: { color: 'rgba(255,255,255,0.85)', fontSize: 12, marginTop: 6 },
  activePeriod: {
    color: 'rgba(255,255,255,0.85)',
    fontSize: 11,
    marginTop: Spacing.sm,
  },
  pill: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: Radius.full,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  pillText: { color: Colors.white, fontSize: 11, fontWeight: '700' },

  emptyActive: {
    backgroundColor: Colors.surface,
    borderRadius: Radius.lg,
    padding: Spacing.md,
    marginTop: Spacing.md,
    ...Shadows.card,
  },
  emptyActiveTitle: { fontSize: 15, fontWeight: '700', color: Colors.text },
  emptyActiveSub: { fontSize: 12, color: Colors.textMuted, marginTop: 4 },

  // kartu paket
  planCard: {
    backgroundColor: Colors.surface,
    borderRadius: Radius.lg,
    padding: Spacing.md,
    marginBottom: Spacing.sm + 4,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  planCurrent: { borderColor: Colors.primary, borderWidth: 2 },
  planHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  planName: { fontSize: 16, fontWeight: '800', color: Colors.text },
  planPrice: {
    fontSize: 15,
    fontWeight: '800',
    color: Colors.primary,
    marginTop: 4,
  },
  planTag: {
    backgroundColor: Colors.primarySoft,
    borderRadius: Radius.full,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  planTagText: { color: Colors.primary, fontSize: 10, fontWeight: '700' },
  planDesc: { fontSize: 12, color: Colors.textMuted, marginTop: Spacing.sm },
  planSpecs: { flexDirection: 'row', marginTop: Spacing.sm, gap: Spacing.md },
  planSpec: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  planSpecText: { fontSize: 11, color: Colors.text, fontWeight: '600' },
  planBtn: {
    marginTop: Spacing.md,
    backgroundColor: Colors.primary,
    borderRadius: Radius.md,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  planBtnText: { color: Colors.white, fontSize: 14, fontWeight: '700' },
  planBtnDisabled: { backgroundColor: Colors.border },
  planBtnTextDisabled: { color: Colors.textMuted },

  // riwayat
  sectionTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: Colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 6,
    marginLeft: 4,
  },
  historyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.surface,
    borderRadius: Radius.md,
    padding: Spacing.sm + 4,
    marginBottom: Spacing.sm,
  },
  historyInfo: { flex: 1 },
  historyPlan: { fontSize: 14, fontWeight: '700', color: Colors.text },
  historyDate: { fontSize: 11, color: Colors.textMuted, marginTop: 2 },
  historyAmount: { fontSize: 13, fontWeight: '700', color: Colors.text },
  statusTag: {
    borderRadius: Radius.full,
    paddingHorizontal: 8,
    paddingVertical: 2,
    marginTop: 4,
    alignSelf: 'flex-start',
  },
  statusTagText: { fontSize: 10, fontWeight: '700' },

  // modal bayar
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalCard: {
    backgroundColor: Colors.surface,
    borderTopLeftRadius: Radius.lg,
    borderTopRightRadius: Radius.lg,
    padding: Spacing.lg,
    paddingBottom: Spacing.xl,
  },
  modalTitle: { fontSize: 18, fontWeight: '800', color: Colors.text },
  modalSub: { fontSize: 13, color: Colors.textMuted, marginTop: 4 },
  methodList: { marginTop: Spacing.md },
  methodRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
    padding: Spacing.md,
    marginBottom: Spacing.sm,
  },
  methodActive: { borderColor: Colors.primary, backgroundColor: Colors.primarySoft },
  methodLabel: { flex: 1, fontSize: 14, fontWeight: '600', color: Colors.text },
  modalActions: { flexDirection: 'row', gap: Spacing.sm, marginTop: Spacing.sm },
  modalBtn: {
    flex: 1,
    minHeight: 50,
    borderRadius: Radius.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalCancel: { backgroundColor: Colors.background, borderWidth: 1, borderColor: Colors.border },
  modalCancelText: { color: Colors.text, fontSize: 15, fontWeight: '700' },
  modalPrimary: { backgroundColor: Colors.primary },
  modalPrimaryText: { color: Colors.white, fontSize: 15, fontWeight: '700' },

  empty: { alignItems: 'center', paddingVertical: Spacing.lg },
  emptyText: { color: Colors.textMuted, marginTop: Spacing.sm },
});
